### ISSUE TITLE
[gardelinux] publish vm-images for azure using community image gallery

### ISSUE THREAD

**Issue by ccwienk** [gardener/cc-utils#680]
To fully automate publishing of Gardenlinux VM Images, also for azure, use azure's community image gallery.

# Sub-Tasks

- [x] enable mcm to consume images from community image gallery
- [x] enable `gardener-azure-extension` for consume images from community image gallery
- [x] adopt Azure CloudProfile generation to allow configuring community gallery images
- [x] change gardenlinux pipeline to publish vm-images for azure through community image gallery

**Comment by ccwienk** [comment]
@MrBatschner | @dkistner : do I correctly understand that Gardener (/ relevant extensions) are now capable of consuming images from community image gallery?

/cc @AndreasBurger

**Comment by MrBatschner** [comment]
Yes, to my understanding, Gardener has got everything to consume CloudProfiles with `communityGalleryImageID` references and create Shoots with them.

**Comment by ccwienk** [comment]
thx @MrBatschner  - unassigning you and @dkistner

**Comment by dkistner** [comment]
Yes, now we can configure community image gallery images in the Azure CloudProfile. It's currently possible on dev, staging and canary. Live will follow after next update.

**Comment by ccwienk** [comment]
first PR w/ gardenlinux-images published via image-gallery already reached gardener
